# Optional ROI to use for the object detection
bool use_roi
float32[] filter_limits
---
# Send the found objects, see the msg files for docs
object_recognition_msgs/RecognizedObjectArray recognized_objects
---
#no feedback
