using System;
using System.Collections.Generic;
using System.Net;
using Iviz.Msgs;

namespace Iviz.Roslib
{
    public class RosPublisher
    {
        readonly TcpSenderManager manager;
        readonly List<string> ids = new List<string>();
        readonly RosClient client;
        readonly Type topicClassType;
        int totalPublishers;

        /// <summary>
        /// Whether this publisher is valid.
        /// </summary>
        public bool IsAlive { get; private set; }
        /// <summary>
        /// The name of the topic.
        /// </summary>
        public string Topic => manager.Topic;
        /// <summary>
        /// The ROS message type of the topic.
        /// </summary>
        public string TopicType => manager.TopicType;
        /// <summary>
        /// The number of publishers in the topic.
        /// </summary>
        public int NumSubscribers => manager.NumConnections;
        /// <summary>
        /// The number of ids generated by this publisher.
        /// </summary>
        public int NumIds => ids.Count;

        /// <summary>
        /// Whether latching is enabled. When active, new subscribers will automatically receive a copy of the last message sent.
        /// </summary>
        public bool LatchingEnabled
        {
            get => manager.Latching;
            set => manager.Latching = value;
        }

        /// <summary>
        /// The queue size in bytes.
        /// If a message arrives that makes the queue larger than this, the oldest message will be discarded.
        /// </summary>
        public int MaxQueueSizeInBytes
        {
            get => manager.MaxQueueSizeInBytes;
            set => manager.MaxQueueSizeInBytes = value;
        }

        /// <summary>
        /// Timeout in milliseconds to wait for a subscriber handshake.
        /// </summary>        
        public int TimeoutInMs
        {
            get => manager.TimeoutInMs;
            set => manager.TimeoutInMs = value;
        }

        public event Action<RosPublisher> NumSubscribersChanged;

        internal RosPublisher(RosClient client, TcpSenderManager manager, Type topicClassType)
        {
            this.client = client;
            this.manager = manager;
            this.topicClassType = topicClassType;
            IsAlive = true;
        }

        void AssertIsAlive()
        {
            if (!IsAlive)
            {
                throw new ObjectDisposedException("This is not a valid publisher");
            }
        }

        string GenerateId()
        {
            string newId = totalPublishers == 0 ? Topic : $"{Topic}-{totalPublishers}";
            totalPublishers++;
            return newId;
        }

        public PublisherTopicState GetState()
        {
            AssertIsAlive();
            Cleanup();
            return new PublisherTopicState(Topic, TopicType, ids.ToArray(), manager.GetStates());
        }

        public void Publish(IMessage message)
        {
            if (message is null)
            {
                throw new ArgumentNullException(nameof(message));
            }

            if (!MessageTypeMatches(message.GetType())) 
            {
                throw new InvalidMessageTypeException("Type does not match publisher.");
            }

            message.RosValidate();
            AssertIsAlive();
            manager.Publish(message);
        }

        public void Cleanup()
        {
            if (manager.Cleanup())
            {
                NumSubscribersChanged?.Invoke(this);
            }
        }

        internal void RequestTopicRpc(string remoteCallerId, out string hostname, out int port)
        {
            IPEndPoint endPoint = manager.CreateConnection(remoteCallerId);
            hostname = manager.CallerUri.Host;
            port = endPoint.Port;

            NumSubscribersChanged?.Invoke(this);
        }

        internal void Stop()
        {
            ids.Clear();
            manager.Stop();
            NumSubscribersChanged = null;
            IsAlive = false;
        }

        public string Advertise()
        {
            AssertIsAlive();

            string id = GenerateId();
            ids.Add(id);

#if DEBUG__
            Logger.LogDebug($"{this}: Advertising '{Topic}' with type {TopicType} and id '{id}'");
#endif

            return id;
        }

        public bool Unadvertise(string topicId)
        {
            if (topicId is null)
            {
                throw new ArgumentNullException(nameof(topicId));
            }

            AssertIsAlive();
            int index = ids.IndexOf(topicId);
            if (index < 0)
            {
                return false;
            }

            ids.RemoveAt(index);

#if DEBUG__
            Logger.LogDebug($"{this}: Unadvertising '{Topic}' with type {TopicType} and id '{topicId}'");
#endif

            if (ids.Count == 0)
            {
                Stop();
                client.RemovePublisher(this);

#if DEBUG__
                Logger.LogDebug($"{this}: Removing publisher '{Topic}' with type {TopicType}");
#endif
            }

            return true;
        }

        public bool ContainsId(string id)
        {
            if (id is null)
            {
                throw new ArgumentNullException(nameof(id));
            }

            return ids.Contains(id);
        }
        
        public bool MessageTypeMatches(Type type)
        {
            return type == topicClassType;
        }        
        
        public override string ToString()
        {
            return $"[Publisher {Topic} [{TopicType}] ]";
        }        
    }
}