# Adds a module

string topic		# Name of the topic
---
bool success		# Whether the retrieval succeeded
string message		# An error message if success is false
string id		# An id identifying this module
