# Retrieves a 3D model, and converts it into a format that can be used in iviz

string uri		# Uri of the file. Example: package://some_package/file.dae
---
bool success		# Whether the retrieval succeeded
Model model		# The 3D model
string message		# An error message if success is false
