# A list of motion commands - one for each section of the sequence
MotionSequenceRequest request

# Planning options
PlanningOptions planning_options
---

# Response comprising information on all sections of the sequence
MotionSequenceResponse response

---

# The internal state that the move group action currently is in
string state
